### ISSUE TITLE
NullPointerException in mxCellRenderer.java

### ISSUE THREAD

**Issue by WolfgangFahl** [jgraph/jgraphx#101]
It looks like when an error occurs in createSVGDocument the whole canvas is not created instead of logging the error and creating the valid parts

`java.lang.NullPointerException at com.mxgraph.util.mxCellRenderer.createSvgDocument(mxCellRenderer.java:179) `

**Comment by davidjgraph** [comment]
Hi, we follow [Stackoverflow guidelines](https://stackoverflow.com/help/how-to-ask) in our issues tracker, non compliance with the guidelines will cause issues to be closed until they comply. Please include a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) for this issue to be opened.

**Comment by WolfgangFahl** [comment]
I've forked jgraphx and intend to add a JUnit Test and supply a pull request. My motivation is lower if the issue is closed before I even got to do the first steps  ... 
 `  mvn test
`
currently says "no tests to run". That is strange.

**Comment by WolfgangFahl** [comment]
trying to render
`<mxGraphModel><root><mxCell id="0"/><mxCell id="1" parent="0"/></root></mxGraphModel>`
also leads to a nullpointer exception.
