### ISSUE TITLE
mxHierarchicalLayout ignores isVertexMovable

### ISSUE THREAD

**Issue by Andreas737** [jgraph/jgraphx#12]
In JGraphX the most layout algorithms don't move vertices which are not movable. Unfortunately mxHierarchicalLayout ignores, whether a vertex is movable or not.

As I know now, it's not possible to take the movable flag into account in this layout algorithm (thanks to David). But for me this functionality is important according to customization aspects (so you can execute the layout algorithm, move some vertices and set the movable flag to false, insert some other vertices and execute the layout algorithm again, without moving the vertices, where the movable flag was set to false). If it is not possible to take account of the movable flag for calculating ranks etc., maybe it's possible to simply not move the vertices, which are "not movable"?

Thanks, Andreas

**Comment by davidjgraph** [comment]
It's not possible to write the hierarchical layout in a generic way that some vertices are ignore and have a valid output.
