### ISSUE TITLE
Feature request: support for-each to iterate over an mxCell's children

### ISSUE THREAD

**Issue by onealj** [jgraph/jgraphx#35]
I frequently find myself typing

    for(int i=0; i<cell.getChildCount(); i++) {
        mxCell child = cell.getChildAt(i);
    }

Going through the graph model `graph.getChildCells(cell)` requires that I keep a reference to the graph whenever I want to access the children. When I have a multiple graphs and cells, this gets unnecessarily complicated.

A cleaner solution for this is to for-loop over the children:

    for (mxICell child : cell) {
        (mxCell) child;
    }

This can be achieved by implementing the `Iterable` interface http://docs.oracle.com/javase/7/docs/api/java/lang/Iterable.html#iterator%28%29

    public interface mxICell extends Iterable<mxICell> { ... }

    public class mxCell implements mxICell {
        public Iterator<mxICell> iterator() {
            return childIterator();
        }
        public Iterator<mxICell> childIterator() {
            return (Iterator<mxICell>)(Iterator<? extends mxICell>)children.iterator();
        }
    }

An example of how this is done in another project:
http://svn.apache.org/viewvc/poi/trunk/src/ooxml/java/org/apache/poi/xssf/usermodel/XSSFRow.java?view=markup method `cellIterator()`

**Comment by bobismijnnaam** [comment]
Why was this closed? It seems like a useful addition to me, and not too hard to implement.

**Comment by alderg** [comment]
Thanks for the suggestion! What requires you to keep a reference to the graph when using mxICell to iterate the children?
