### ISSUE TITLE
Why the jgraphx in maven central repo is so old?

### ISSUE THREAD

**Issue by mcheung63** [jgraph/jgraphx#40]
Hi Why the jgraphx in maven central repo is so old?
https://maven-repository.com/artifact/org.tinyjee.jgraphx/jgraphx
thanks
Peter.

**Comment by alderg** [comment]
Whoever put it there doesn't seem to have updated it.

**Comment by vidakovic** [comment]
Sorry to answer to a closed issue... but it's related. I needed this recently and created a script to automatize the publishing process to Maven Central. See here:44

http://search.maven.org/#artifactdetails|com.github.monkeysintown|jgraphx|3.1.2.1|jar

At the moment only the recent version, but the script can publish all (that are visible on Github).

Let me know if you need it.

**Comment by alderg** [comment]
Try to contact whoever published it. We do not have access to it.

**Comment by mcheung63** [comment]
thank you guys
