### ISSUE TITLE
String.isEmpty() in mxGraphicsCanvas2D 

### ISSUE THREAD

**Issue by opicarelli** [jgraph/jgraphx#41]
Hi, the project is using jdk 1.5 (pom.xml <maven.compiler...) and the method String.isEmpty() was added since 1.6... Please check the best way to fix it... or change the algorith (line 1098) or change de compiler maven (pom.xml).

Thanks

**Comment by davidjgraph** [comment]
Changed in repo, though note we don't really support Maven because it's a fucking stinking pile of shit :).

**Comment by opicarelli** [comment]
Thanks anyway!
