### ISSUE TITLE
mxHierarchicalLayout is buggy when applied to hierarchical models

### ISSUE THREAD

**Issue by Ltty** [jgraph/jgraphx#5]
mxHierarchicalLayout still causes problems, if you have groups with different parents. You still have to extend the layout and set traverseAncestors to false, otherwise groups are misplaced in the graph, if foldCells is set to true before the layout process.

![screenshot_01](https://f.cloud.github.com/assets/3204769/47017/ee1d895e-58ac-11e2-8931-4cefe543a460.png)

**Comment by albertotn** [comment]
I have same issue described here: http://stackoverflow.com/questions/32758018/mxhierarchicallayout-not-working-as-expected

**Comment by albertotn** [comment]
Is this project alive ?

**Comment by albertotn** [comment]
A quick workaround for this is to use mxHierarchicalLayout but also put your coordinate inside cell's geometry. Is NOT the right thing to do, but could save your day

**Comment by davidjgraph** [comment]
@Ltty If you take the latest https://github.com/jgraph/jgraphx/blob/master/src/com/mxgraph/layout/hierarchical/mxHierarchicalLayout.java that has a change that ignores the cells within the collapsed cell and will lay it out correctly.

The other two reporters, whereas, your issues may well be valid, they are not reporting the same thing. I'll mark this issue closed, since the original report is resolved.

**Comment by albertotn** [comment]
Sorry, can you explain how to report? Do I need to open a new issue for my problem ?

**Comment by davidjgraph** [comment]
@albertotn Yes, just open a new issue.

**Comment by AttilaOrs** [comment]
Hey, 
I know that this bug is pretty old but i have an almot working example [here](https://gist.github.com/AttilaOrs/630286f0172d98a9a5ca76649c1705c7). I hopes it helps some

**Comment by loizbak** [comment]
Hello,

I seems that cross-groups edges have wrong jetties and ranks.
I wrote a patch that resets jetties and ranks for such edges.
With this patch, edges arrows are straight which is better but not acceptable if they are numerous.

Patched layout:
[patch.zip](https://github.com/jgraph/jgraphx/files/1532416/patch.zip)

To try it:

// Patched Layout graph
PatchedHierarchicalLayout layout = new PatchedHierarchicalLayout( graph );
mxHierarchicalLayout layout = new mxHierarchicalLayout( graph );
layout.setFineTuning( true );
layout.execute( parent );
