### ISSUE TITLE
Bug: Movings cells

### ISSUE THREAD

**Issue by psychonetic** [jgraph/jgraphx#52]
I try to move all cells of a graph to another position at once:
````
Object[] ver = graph.getChildVertices(graph.getDefaultParent());
graph.moveCells(ver, 100, 100, false);
````

The result:
![image](https://cloud.githubusercontent.com/assets/4885172/12644542/c1b032ae-c5c3-11e5-8ec0-bf2d98965d32.png)

I guess this is not the desired behavior. I also tried	graph.resetEdges(graph.getEdges(graph.getDefaultParent()));

but nothing changed.

So, how can I move the start and endpoints of the edges back to its normal positions?
(like the image below, before I moved the cells)
![image](https://cloud.githubusercontent.com/assets/4885172/12644578/09abd888-c5c4-11e5-9255-80913801ab71.png)

**Comment by davidjgraph** [comment]
This is an issue tracker, not a general help forum. Try Stackoverflow for general help.

**Comment by psychonetic** [comment]
This is a bug or is the result desired as shown on the pictures?
