### ISSUE TITLE
mxGraphSelection swapping added and removed in change event

### ISSUE THREAD

**Issue by bobismijnnaam** [jgraph/jgraphx#54]
I'll get right to the point: in mxGraphSelection.execute() the following happens:

```
			if (removed != null)
			{
				Iterator<Object> it = removed.iterator();

				while (it.hasNext())
				{
					model.cellRemoved(it.next());
				}
			}

			if (added != null)
			{
				Iterator<Object> it = added.iterator();

				while (it.hasNext())
				{
					model.cellAdded(it.next());
				}
			}

			Collection<Object> tmp = added;
			added = removed;
			removed = tmp;
			model.fireEvent(new mxEventObject(mxEvent.CHANGE, "added", added,
					"removed", removed));
```

Now maybe it's me, but when the code first removes a bunch of cells, and then adds them, I'd expect the broadcasted event to tell me that the added cells are added, and the removed cells are removed. And not the other way around, as the bottom 4 lines make sure. In short: why are added and removed swapped around so they are effectively telling the opposite? Is this a bug or do I have a warped perception of causality?

**Comment by alderg** [comment]
It's a bug, but we can't fix it without breaking all existing listeners. We could add another event with the names fixed, but since it's trivial to address this in the listener this won't be added for now.

**Comment by bobismijnnaam** [comment]
Alright, thanks for your quick response! Maybe a comment can be added for the documentation?

**Comment by alderg** [comment]
Yep, will add a comment.
