### ISSUE TITLE
mxGraph.cloneCells is not recursive

### ISSUE THREAD

**Issue by bobismijnnaam** [jgraph/jgraphx#58]
As far as I can tell from the source cloneCells is not recursive. That is, the cloned cells share their children with the original. Can a cloneCellsRec method be added and documentation changed, or maybe the cloneCells function made recursive such that children are also cloned?

Or should I use an other function for recursive cloning?

**Comment by onealj** [comment]
Java clone methods have this problem. I prefer copy constructor over clone
methods, giving you freedom of the type of object that is created.

**Comment by alderg** [comment]
mxGraph.cloneCells uses mxGraphModel.cloneCells, which is recursive.

**Comment by bobismijnnaam** [comment]
Jup, I just found that out myself. It is still quite hard to find though. Maybe add mxGraphModel.cloneCells to the "see also" section of mxGraph.cloneCells?

**Comment by alderg** [comment]
We'll add a reference to mxGraphModel.cloneCells and also state that the clones are recursive.
