### ISSUE TITLE
HOW TO VISUALIZE EDGES AND REMOVE COMPONENTS USING JGRAPHT

### ISSUE THREAD

**Issue by gentlemanjos1** [jgraph/jgraphx#63]
Hello

I am working with JGRAPHT and based on the visualization demo I managed to add and also display vertexes or nodes in a JFrame using JGRAPHT; but when I try to display edges after adding them in JFrame canvas, I doesn´t work and even when I try to graphically remove a component from the Graph, I just does not remove anything.

So please, I need to be explained and guided about graphically (canvas) removing graph componets (edges and vertexes) and about displaying edges betwween vertexes in canvas.

Thank you everyone for your help

**Comment by davidjgraph** [comment]
Github issues isn't a place for people to write your software for you / receive free personal . Post your questions to StackOverflow, http://stackoverflow.com/questions/tagged/jgraphx
