### ISSUE TITLE
getShortestPath function and mxDoubleValCostFunction() NOT WORKING

### ISSUE THREAD

**Issue by gentlemanjos1** [jgraph/jgraphx#65]
Hello

I am trying to use getShortestPath and mxDoubleValCostFunction() function (based on the jgraphx API) in order to get the cost of the shortest path in a graph, but each time I try to run the function, I get a java.lang.NullPointerException and I don´t understand why.

The following is the code of the function I am trying to implement:
`public double optimalSolution(Object startNode, Object endNode)`
	`{ `		
		`mxICostFunction cf=new mxDoubleValCostFunction();`
		`int steps = graph.getChildVertices(parent).length;`
		`Object[] shortPath=mxGraphAnalysis.getInstance().getShortestPath(graph, startNode,  endNode, cf, steps, false);`
		`mxCellState[] states=graph.getView().getCellStates(shortPath);`
		`double sum=0;`		
		`for(int ed=0;ed<states.length;ed++)`
		`{`			
			`sum+=cf.getCost(states[ed]);`		
		`}`		
		`return sum;`		
	`}`

The followning is the code I am using to call the function specified above:
`Object n1=act.getGraph().getModel().getValue("N1"); // Starting Node.`
`Object n2=act.getGraph().getModel().getValue("N4");	// Ending Node.`			
`double sol=act.optimalSolution(n1, n2);`				
`textFieldOSolution.setText(""+sol);`

Please I need to know what I am doing wrong and if possible to be guided in how to solve the problem.

Thank you very much for your attention and sooner answer.

**Comment by alderg** [comment]
If you could create a runnable test case that would help us to resolve this issue faster.

**Comment by gentlemanjos1** [comment]
Thank you very much for your interest, I already solved the problem, anyway and one again, thanks for your help
