### ISSUE TITLE
After clone,Index.html not working.

### ISSUE THREAD

**Issue by agarwalsween** [jgraph/jgraphx#69]

**Comment by agarwalsween** [comment]
It only shows Loading.....

**Comment by davidjgraph** [comment]
This is not a bug report.

**Comment by agarwalsween** [comment]
Then how could I use this source Code.What mistakes I am doing.Please tell me.

**Comment by davidjgraph** [comment]
Find a software engineer and have them explain it to you.

**Comment by agarwalsween** [comment]
ok.thanku sir.
