### ISSUE TITLE
Event properties passed on mxEvent.CHANGE are inverted

### ISSUE THREAD

**Issue by Coniglioz** [jgraph/jgraphx#7]
When a mxEvent.CHANGE event is fired by a mxGraphSelectionModel source, the mxEventObject that is passed has two attributes: "added" and "removed". The first contains cells that have been recently deselected and the second contains the added ones. Should not be the opposite?

**Comment by rlamarche** [comment]
The bug is here : https://github.com/jgraph/jgraphx/blob/master/src/com/mxgraph/view/mxGraphSelectionModel.java#L386

		public void execute()
		{
			if (removed != null)
			{
				Iterator<Object> it = removed.iterator();

				while (it.hasNext())
				{
					model.cellRemoved(it.next());
				}
			}

			if (added != null)
			{
				Iterator<Object> it = added.iterator();

				while (it.hasNext())
				{
					model.cellAdded(it.next());
				}
			}

			Collection<Object> tmp = added;
			added = removed;
			removed = tmp;
			model.fireEvent(new mxEventObject(mxEvent.CHANGE, "added", added,
					"removed", removed));
		}

**Comment by alderg** [comment]
Thanks for the feedback. This is a known issue, unfortunately it cannot be changed at this point to avoid breaking existing code.
