### ISSUE TITLE
Wrong license information for mxGraph

### ISSUE THREAD

**Issue by cdhermann** [jgraph/jgraphx#70]
The file https://github.com/jgraph/jgraphx/blob/master/README.md states in the first paragraph that mxGraph is not open source. The license file https://github.com/jgraph/mxgraph/blob/master/LICENSE of mxGraph indicates an Apache 2.0 license which is considered a free software license. In my opinion this qualifies mxGraph as an open source software.

**Comment by davidjgraph** [comment]
Fixed
