### ISSUE TITLE
XML Help

### ISSUE THREAD

**Issue by helmutkemper** [jgraph/jgraphx#73]
Please, where do I find a manual how to draw with xml?

**Comment by helmutkemper** [comment]
I can use the 2d drawing commands in xml, move, line, text, fillcolor. However, where do I get a complete list of commands to draw something using xml?

**Comment by alderg** [comment]
https://desk.draw.io/support/solutions/articles/16000052874-how-to-create-and-edit-shapes-

**Comment by danilomo** [comment]
Do we need to create shapes manually by writing XML?

There's no way to convert SVG into a shape XML?

**Comment by alderg** [comment]
See https://github.com/jgraph/svg2xml
