### ISSUE TITLE
mxUtils.loadDocument always returns null

### ISSUE THREAD

**Issue by ekauffmann** [jgraph/jgraphx#78]
**Context:** I have been trying to compile the class `GraphEditor.java` in the examples folder, and it always threw a `NullPointerException` in line 469. At first I thought it wasn't able to find the path to default-style.xml, but it was actually correct after a quick inspection through debugging.

**Problem:** On line 469 from GraphEditor, as the variable `doc` is always set as null in line 466, `getElement()` throws `NullPointerException`. The problem was found inside the method `loadDocument` in the class `mxUtils`, which is **always** returning null. A possible solution would involve adding a return statement inside the try-catch block of `loadDocument`, or at least inside de try block.
```java
public static Document loadDocument(String var0) {
        try {
            mxXmlUtils.getDocumentBuilder().parse(var0);
            // here should be a return statement
        } catch (Exception var2) {
            var2.printStackTrace();
        }

        return null;
    }
```

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release.
