### ISSUE TITLE
did mxCell support SVG style(image)

### ISSUE THREAD

**Issue by drogbababa** [jgraph/jgraphx#89]
I put a png image into a mxCell, but when zoom in, the image got blury. So can mxcell support SVG format image so that zooming won't cause vague.

**Comment by davidjgraph** [comment]
Yes, it supports SVG in the same way it supports any image.

**Comment by drogbababa** [comment]
Thanks for answering. Could you show me a few lines code of initializing a vertex(mxCell) by SVG.
Currently, I'm using 
`safetyTreeGraph.insertVertex(parent, null, myObject, width, height, 120,50,"RECT_LOGICAL_STYLE");`
and RECT_LOGICAL_STYLE is a style name which contains a png image, it's something like this,
`myStyle.put(mxConstants.STYLE_IMAGE, "/resource/icon/porte_et.png");`
So how could I replace porte_et.png to SVG. btw ,I have converted png to svg using a online tool.
Shoul I use mxSvgCanvas?
