### ISSUE TITLE
Edges don't allow me to choose exact points in source or target

### ISSUE THREAD

**Issue by jevora** [jgraph/jgraphx#92]
Good morning,

I'm not sure if this is the best place to ask questions about this library. I hope it is.

I'm developing a tool for modelling graphs and I don't see how an edge can be painted choosing both terminal points. If I have an elbow, I can define where one of the terminal points will be but the other terminal point may or not be precise depending on the location of the arrows. Let me try to explain it with images:

In this first image, I can move the elbow enough so that the terminal point of the target of the edge can be placed where I want. However, the source terminal point cannot be defined and it will always be stacked at vertical centre of the block
![image](https://user-images.githubusercontent.com/5517331/36969904-b280343a-205e-11e8-82b0-2076c7699399.png)

If I want to precisely define the terminal point of the source block, then I loose precision in the target terminal point:
![image](https://user-images.githubusercontent.com/5517331/36970014-fe15d29c-205e-11e8-85fd-53e9f52e17c2.png)

I have tried to figure it out how to make possible to configure both terminal points precisely. However I haven't managed to do it. I have been looking for the possibility of having two elbows, which would allow me to define both terminal points, but I haven't seen how to do it. Additionally, I've tried to find a way to move terminal points but I haven't succeed.

Thanks!

**Comment by davidjgraph** [comment]
Stackoverflow is the correct place to ask. I see you've already double posted there, https://stackoverflow.com/questions/49109471/edges-dont-allow-me-to-choose-exact-points-in-source-or-target-mxgraph, so I'll close this question.

**Comment by jevora** [comment]
Thanks @davidjgraph . Unfortunately, I haven't received an answer. Maybe you know how to do it in case it is possible?
